packages:
  - packages/*
  - packages/drei/dist
  - packages/react-three-fiber/packages/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - esbuild
